"""Updated Parent Model

Revision ID: 22e094bd3caf
Revises: 988bb2102d97
Create Date: 2025-04-13 20:50:52.430635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e094bd3caf'
down_revision = '988bb2102d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('payment_date', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_customer', schema=None) as batch_op:
        batch_op.drop_column('payment_date')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
