"""new payment

Revision ID: 72421041a816
Revises: 8c009496d32b
Create Date: 2025-06-14 11:34:24.591961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72421041a816'
down_revision = '8c009496d32b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('payment_date')

    # ### end Alembic commands ###
