"""New Payment Model

Revision ID: 7b959b3c4f81
Revises: fe4ce288c27d
Create Date: 2025-05-20 20:15:12.413550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b959b3c4f81'
down_revision = 'fe4ce288c27d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_customer', schema=None) as batch_op:
        batch_op.drop_column('payment_date')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('payment_date', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
