"""new payments

Revision ID: 8c009496d32b
Revises: 
Create Date: 2025-06-14 11:28:30.684729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c009496d32b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.String(length=50), nullable=True))
        batch_op.drop_column('payment_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
