"""Updated Student Model

Revision ID: 988bb2102d97
Revises: c7af236e1442
Create Date: 2025-04-12 11:55:22.151212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988bb2102d97'
down_revision = 'c7af236e1442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_contact', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('parent_contact')

    # ### end Alembic commands ###
