"""Updated Batch model: replaced start_date and end_date with start_time and end_time

Revision ID: c7af236e1442
Revises: 
Create Date: 2025-04-12 11:26:36.621568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7af236e1442'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.String(length=50), nullable=False))
        batch_op.drop_column('start_date')
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
