"""Updated Parent Model

Revision ID: fe4ce288c27d
Revises: 22e094bd3caf
Create Date: 2025-04-14 21:31:47.779807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe4ce288c27d'
down_revision = '22e094bd3caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_of_months', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_customer', schema=None) as batch_op:
        batch_op.drop_column('no_of_months')

    # ### end Alembic commands ###
